name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'
    - name: Package install
      run: yarn install --immutable
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
