name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"
          cache: "yarn"
      - name: Package install
        run: yarn install --immutable
      - name: Format
        run: yarn format:check
      - name: Typecheck
        run: yarn typecheck
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
